[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/ws/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/client/index.html"
  status = 200 